# config/imapp_config.yml


# カラム名の変換マッピング（整形後の列名）
column_rename_map:
  Country: country
  ifscode: ifs_code
  iso3: country_code_iso3
  iso2: country_code
  AE: advanced
  EMDE: emerging
  Year: year
  Month: month
  variable: indicator
  value: flag
  Quarter: quarter


# 最終出力CSVに保持する列の順序
output_columns:
  - country
  - ifs_code
  - iso3c
  - iso2c
  - advanced
  - emerging
  - year
  - month
  - quarter
  - indicator
  - flag
