# Variable Configuration for Macroprudential Policy Analysis
# Variables can be enabled/disabled and modified as analysis evolves

# Dependent Variable (always required)
dependent_variable:
  tightening:
    name: "Macroprudential Policy Tightening"
    description: "Binary indicator for macroprudential policy tightening actions"
    source: "IMF_iMaPP"
    data_type: "binary"
    unit: "0/1"
    role: "dependent"
    required: true
    enabled: true

# Core Explanatory Variables (baseline model)
explanatory_variables:
  # Credit-related variables
  credit_gap:
    name: "Credit-to-GDP Gap"
    description: "Deviation of credit-to-GDP ratio from long-term trend using HP filter"
    source: "BIS"
    dataset: "CREDIT_GAPS"
    data_type: "continuous"
    unit: "percentage_points"
    transformation: "none"  # Already gap-transformed by BIS
    role: "explanatory"
    category: "credit"
    enabled: true
    priority: "high"
    
  credit_nf:
    name: "Credit to Non-Financial Sector"
    description: "Total credit to non-financial sector as percentage of GDP"
    source: "BIS"
    dataset: "TOTAL_CREDIT"
    data_type: "continuous"
    unit: "percent_gdp"
    transformation: "level"  # Can be changed to growth rates
    role: "explanatory"
    category: "credit"
    enabled: true
    priority: "medium"
    
  debt_service:
    name: "Debt Service Ratio"
    description: "Debt service payments as percentage of income"
    source: "BIS"
    dataset: "DSR"
    data_type: "continuous"
    unit: "percent"
    transformation: "level"
    role: "explanatory"
    category: "credit"
    enabled: true
    priority: "medium"

  # Asset price variables
  house_prices:
    name: "Residential Property Prices"
    description: "Real residential property price growth"
    source: "BIS"
    dataset: "RPP"
    data_type: "continuous"
    unit: "percent"
    transformation: "yoy_growth"  # Year-over-year growth rate
    role: "explanatory"
    category: "asset_prices"
    enabled: true
    priority: "high"
    
  comm_prices:
    name: "Commercial Property Prices"
    description: "Real commercial property price growth"
    source: "BIS"
    dataset: "CPP"
    data_type: "continuous"
    unit: "percent"
    transformation: "yoy_growth"
    role: "explanatory"
    category: "asset_prices"
    enabled: true
    priority: "low"

  # External/monetary variables  
  reer:
    name: "Real Effective Exchange Rate"
    description: "Trade-weighted real effective exchange rate growth"
    source: "BIS"
    dataset: "EER"
    data_type: "continuous"
    unit: "percent"
    transformation: "yoy_growth"
    role: "explanatory"
    category: "external"
    enabled: true
    priority: "low"
    
  policy_rate:
    name: "Central Bank Policy Rate"
    description: "Official central bank policy interest rate"
    source: "BIS"
    dataset: "CBPOL"
    data_type: "continuous"
    unit: "percent"
    transformation: "level"  # Can be changed to changes
    role: "explanatory"
    category: "monetary"
    enabled: true
    priority: "medium"

# Additional Variables (disabled by default, can be enabled later)
additional_variables:
  # Additional credit variables
  household_debt:
    name: "Household Debt-to-GDP"
    description: "Household debt as percentage of GDP"
    source: "BIS"
    dataset: "DEBT_SEC"
    data_type: "continuous"
    unit: "percent_gdp"
    transformation: "level"
    role: "explanatory"
    category: "credit"
    enabled: false
    priority: "medium"
    
  corporate_debt:
    name: "Corporate Debt-to-GDP"
    description: "Non-financial corporate debt as percentage of GDP"
    source: "BIS"
    dataset: "DEBT_SEC"
    data_type: "continuous"
    unit: "percent_gdp"
    transformation: "level"
    role: "explanatory"
    category: "credit"
    enabled: false
    priority: "medium"

  # Additional asset price variables
  equity_prices:
    name: "Equity Price Index"
    description: "Stock market price index growth"
    source: "OECD"
    dataset: "EQUITY_PRICES"
    data_type: "continuous"
    unit: "percent"
    transformation: "yoy_growth"
    role: "explanatory"
    category: "asset_prices"
    enabled: false
    priority: "low"

  # Macroeconomic variables
  gdp_growth:
    name: "GDP Growth"
    description: "Real GDP growth rate"
    source: "OECD"
    dataset: "GDP"
    data_type: "continuous"
    unit: "percent"
    transformation: "yoy_growth"
    role: "explanatory"
    category: "macro"
    enabled: false
    priority: "medium"
    
  output_gap:
    name: "Output Gap"
    description: "Deviation of GDP from potential output"
    source: "OECD"
    dataset: "OUTPUT_GAP"
    data_type: "continuous"
    unit: "percent"
    transformation: "level"
    role: "explanatory"
    category: "macro"
    enabled: false
    priority: "medium"
    
  inflation:
    name: "Consumer Price Inflation"
    description: "Year-over-year consumer price inflation"
    source: "OECD"
    dataset: "CPI"
    data_type: "continuous"
    unit: "percent"
    transformation: "yoy_growth"
    role: "explanatory"
    category: "macro"
    enabled: false
    priority: "low"

  # Financial market variables
  bond_yields:
    name: "Government Bond Yields"
    description: "10-year government bond yields"
    source: "OECD"
    dataset: "BOND_YIELDS"
    data_type: "continuous"
    unit: "percent"
    transformation: "level"
    role: "explanatory"
    category: "financial"
    enabled: false
    priority: "low"
    
  credit_spreads:
    name: "Corporate Credit Spreads"
    description: "Corporate bond spreads over government bonds"
    source: "BIS"
    dataset: "CREDIT_SPREADS"
    data_type: "continuous"
    unit: "basis_points"
    transformation: "level"
    role: "explanatory"
    category: "financial"
    enabled: false
    priority: "low"

# Variable Selection Presets
variable_sets:
  # Core model (7 variables)
  baseline:
    - credit_gap
    - credit_nf
    - debt_service
    - house_prices
    - comm_prices
    - reer
    - policy_rate
    
  # Minimal model (key variables only)
  minimal:
    - credit_gap
    - house_prices
    - policy_rate
    
  # Credit-focused model
  credit_focus:
    - credit_gap
    - credit_nf
    - debt_service
    - household_debt
    - corporate_debt
    
  # Asset price-focused model
  asset_focus:
    - credit_gap
    - house_prices
    - comm_prices
    - equity_prices
    
  # Extended model (baseline + macro)
  extended:
    - credit_gap
    - credit_nf
    - debt_service
    - house_prices
    - comm_prices
    - reer
    - policy_rate
    - gdp_growth
    - inflation

# Transformation Options
transformations:
  level: "Use variable as-is"
  yoy_growth: "Year-over-year growth rate (4-quarter change for quarterly data)"
  qoq_growth: "Quarter-over-quarter growth rate"
  log_level: "Natural logarithm of level"
  first_difference: "First difference (quarter-to-quarter change)"
  hp_filter: "HP filter cyclical component"
  standardized: "Z-score standardization"

# Data Frequency Handling
frequency_settings:
  target_frequency: "quarterly"
  
  # Conversion rules for different data sources
  conversion_rules:
    # IMF iMaPP (monthly) → quarterly conversion
    tightening:
      source_frequency: "monthly"
      target_frequency: "quarterly"
      
      # Multiple dependent variables for comprehensive analysis
      variables:
        # Primary: Binary approach
        tightening_binary:
          method: "any_action"
          interpretation: "Binary indicator: 1 if any tightening in quarter, 0 otherwise"
          use_case: "Main analysis - policy regime identification"
          theoretical_basis: "Taylor rule framework - policy direction"
          
        # Secondary: Intensity approach  
        tightening_intensity:
          method: "sum_actions"
          interpretation: "Count of tightening actions per quarter (0, 1, 2, 3...)"
          use_case: "Intensity analysis - policy strength assessment"
          theoretical_basis: "Captures policy urgency and severity"
          
        # Tertiary: Categorical approach
        tightening_categorical:
          method: "intensity_categories"
          categories:
            0: "No tightening"
            1: "Single measure (moderate concern)"
            2: "Multiple measures (high concern)"
          interpretation: "Ordinal measure of policy intensity"
          use_case: "Ordered logit/probit analysis"
          
      # Analysis framework for multi-faceted approach
      analysis_strategy:
        stage_1_baseline:
          dependent_var: "tightening_binary"
          model_type: "logit/probit"
          purpose: "Establish baseline Taylor rule relationships"
          
        stage_2_intensity:
          dependent_var: "tightening_intensity" 
          model_type: "poisson/negative_binomial"
          purpose: "Examine policy intensity determinants"
          
        stage_3_categorical:
          dependent_var: "tightening_categorical"
          model_type: "ordered_logit/probit"
          purpose: "Analyze graduated policy responses"
          
        stage_4_robustness:
          approach: "compare_all_measures"
          purpose: "Validate consistency across specifications"
          
      # Multiple actions interpretation framework
      intensity_interpretation:
        single_action: |
          Single tightening measure indicates:
          - Targeted response to specific risk
          - Moderate policy concern
          - Standard regulatory adjustment
          
        multiple_actions: |
          Multiple tightening measures indicate:
          - Broad-based financial stability concerns
          - Urgent policy response required
          - Systemic risk perception by authorities
          - Coordinated policy package approach
    
    # BIS data (already quarterly)
    credit_gap:
      source_frequency: "quarterly"
      target_frequency: "quarterly" 
      method: "native"  # No conversion needed
      
    credit_nf:
      source_frequency: "quarterly"
      target_frequency: "quarterly"
      method: "native"
      
    debt_service:
      source_frequency: "quarterly" 
      target_frequency: "quarterly"
      method: "native"
      
    house_prices:
      source_frequency: "quarterly"
      target_frequency: "quarterly"
      method: "native"
      
    comm_prices:
      source_frequency: "quarterly"
      target_frequency: "quarterly"
      method: "native"
      
    reer:
      source_frequency: "monthly"  # BIS provides monthly
      target_frequency: "quarterly"
      method: "end_quarter"  # Use end-of-quarter value
      alternative_methods:
        - "average"          # Quarterly average
        - "growth_rate"      # Quarterly growth rate
      
    policy_rate:
      source_frequency: "monthly"  # BIS provides monthly
      target_frequency: "quarterly" 
      method: "end_quarter"  # Use end-of-quarter rate
      alternative_methods:
        - "average"          # Quarterly average rate

# Data Quality Requirements
quality_requirements:
  minimum_coverage: 0.75  # 75% of observations must be non-missing
  maximum_outliers: 0.05  # Maximum 5% outliers per variable
  required_frequency: "quarterly"
  
# BIS API Configuration
bis_api:
  base_url: "https://stats.bis.org/api/v2/data/dataflow/BIS"
  format: "csv"  # Recommended: csv, json, sdmx
  frequency: "Q"  # Quarterly data
  
  # API endpoints for each variable
  endpoints:
    credit_gap:
      dataset: "WS_CREDIT_GAP"
      format: "csv"
      
    credit_nf:
      dataset: "WS_TOTAL_CREDIT"
      format: "csv"
      
    debt_service:
      dataset: "WS_DSR"
      format: "csv"
      
    house_prices:
      dataset: "WS_RPP"
      format: "csv"
      
    comm_prices:
      dataset: "WS_CPP"
      format: "csv"
      
    reer:
      dataset: "WS_EER"
      format: "csv"
      
    policy_rate:
      dataset: "WS_CBPOL"
      format: "csv"